version: '3.1'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jazztech?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"
    volumes:
      - jazztech_data:/var/lib/mysql

  app:
    build: .
    image: spring-boot-docker-jar
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      <<: *database-variables

volumes:
  jazztech_data:


