server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jazztech?createDatabaseIfNotExist=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: SpringBootMysqlPool
  jpa:
    hibernate:
      ddl-auto: update